In [ ]:
import seaborn as sns
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
train_df =pd.read_csv('/content/train.csv')
test_df =pd.read_csv('/content/test.csv')
combine =[train_df, test_df]
frame = pd.DataFrame(data=train_df)
frame2 = pd.DataFrame(data=test_df)
from sklearn import tree
import pydotplus
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
import matplotlib.image as pltimg
from sklearn import svm, datasets 

frame['Gender'] = 0
frame2['Gender'] = 0
for i in range(len(frame['Sex'])):
  if(frame['Sex'][i] == 'female'):
    frame.at[i,'Gender'] = 1
for i in range(len(frame2['Sex'])):
  if(frame2['Sex'][i] == 'female'):
    frame2.at[i,'Gender'] = 1  

import random
find = frame['Age'].isnull()
for i in range(len(frame['Age'])):
  if(find[i] == True):
    frame.at[i,'Age'] = random.randint(0,81)
find = frame2['Age'].isnull()
for i in range(len(frame2['Age'])):
  if(find[i] == True):
    frame2.at[i,'Age'] = random.randint(0,81)

find = frame['Embarked'].isnull()
for i in range(len(frame['Embarked'])):
  if(find[i] == True):
    frame.at[i,'Embarked'] = 'S'
find = frame2['Embarked'].isnull()
for i in range(len(frame2['Embarked'])):
  if(find[i] == True):
    frame2.at[i,'Embarked'] = 'S'

mod = frame['Fare'].mode()
for i in range(len(frame['Fare'])):
  if(frame['Fare'][i] == 0):
    frame.at[i,'Fare'] = mod
mod = frame2['Fare'].mode()
for i in range(len(frame2['Fare'])):
  if(frame2['Fare'][i] == 0):
    frame2.at[i,'Fare'] = mod

frame['AgeBand'] = 0
frame2['AgeBand'] = 0
for i in range(len(frame['Age'])):
  if(frame['Age'][i] > 20.125 and frame['Age'][i] <= 28):
    frame.at[i,'AgeBand'] = 1
  if(frame['Age'][i] > 28 and frame['Fare'][i] <= 38.0):
    frame.at[i,'AgeBand'] = 2
  if(frame['Age'][i] >38.0):
    frame.at[i,'AgeBand'] = 3
for i in range(len(frame2['Fare'])):
  if(frame2['Age'][i] >20.125 and frame2['Age'][i] <= 28):
    frame2.at[i,'AgeBand'] = 1
  if(frame2['Age'][i] >28 and frame2['Age'][i] <= 38.0):
    frame2.at[i,'AgeBand'] = 2
  if(frame2['Age'][i] >38.0):
    frame2.at[i,'AgeBand'] = 3 

In [ ]:
features=['Pclass','Gender','AgeBand']
x = train_df[features]
y = train_df['Survived']
svc = svm.SVC(kernel ='linear', C = 1).fit(x,y)
svc

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(svc,x,y,cv=5))

[0.80446927 0.80337079 0.78651685 0.75280899 0.78651685]


In [ ]:
svq = svm.SVC(kernel='poly', gamma=1, C=1).fit(x,y)
svq

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
print(cross_val_score(svq,x,y,cv=5))

[0.74860335 0.79775281 0.76966292 0.75280899 0.78651685]


In [ ]:
svrbf = svm.SVC(kernel='rbf', gamma=5, C=1).fit(x,y)
svrbf


SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=5, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
print(cross_val_score(svrbf,x,y,cv=5))

[0.73743017 0.7752809  0.78089888 0.75842697 0.76966292]


In [ ]:
x = [[ -1,-1],[-1,1],[1,-1],[1,1]]
y = [0,1,1,0]
svc = svm.SVC(kernel ='linear',C = 1).fit(x,y)
svc

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)